package fi.otavanopisto.pyramus.matriculation;

public enum MatriculationExamGrade {
  IMPROBATUR,
  APPROBATUR,
  LUBENTER_APPROBATUR,
  CUM_LAUDE_APPROBATUR,
  MAGNA_CUM_LAUDE_APPROBATUR,
  EXIMIA_CUM_LAUDE_APPROBATUR,
  LAUDATUR,
  UNKNOWN,
  NO_RIGHT_TO_PARTICIPATE,
  INVALIDATED,
  K
}
