({
	'run' : function(api){
	  api.log('Importing modules...');
    
    var data = [
      {"subject":"AT","cnum":1,"name":"Laitteen käyttö ja tiedonhallinta"},
      {"subject":"AT","cnum":2,"name":"Tekstinkäsittely"},
      {"subject":"AT","cnum":3,"name":"Internet"},
      {"subject":"AT","cnum":4,"name":"Taulukkolaskenta"},
      {"subject":"AT","cnum":5,"name":"Tietokanta"},
      {"subject":"AT","cnum":6,"name":"Esitysgrafiikka ja piirtäminen"},
      {"subject":"AT","cnum":7,"name":"Tietotekniikan perusteet"},
      {"subject":"BI","cnum":1,"name":"Eliömaailma"},
      {"subject":"BI","cnum":2,"name":"Solu ja perinnöllisyys"},
      {"subject":"BI","cnum":3,"name":"Ympäristöekologia"},
      {"subject":"BI","cnum":4,"name":"Ihmisen biologia"},
      {"subject":"BI","cnum":5,"name":"Bioteknologia"},
      {"subject":"EAB3","cnum":1,"name":"Hyvää päivää, hauska tutustua"},
      {"subject":"EAB3","cnum":2,"name":"Näin asiat hoituvat"},
      {"subject":"EAB3","cnum":3,"name":"Vapaa-aika ja harrastukset"},
      {"subject":"EAB3","cnum":4,"name":"Meillä ja muualla"},
      {"subject":"EAB3","cnum":5,"name":"Ennen ja nyt"},
      {"subject":"EAB3","cnum":6,"name":"Opiskelu ja tulevaisuudensuunnitelmat"},
      {"subject":"ENA","cnum":1,"name":"Minä ja muut"},
      {"subject":"ENA","cnum":2,"name":"Viestintä ja vapaa-aika"},
      {"subject":"ENA","cnum":3,"name":"Opiskelu ja työ"},
      {"subject":"ENA","cnum":4,"name":"Yhteiskunta ja ympäröivä maailma"},
      {"subject":"ENA","cnum":5,"name":"Kulttuuri"},
      {"subject":"ENA","cnum":6,"name":"Tiede, talous ja tekniikka"},
      {"subject":"ENA","cnum":7,"name":"Luonto ja kestävä kehitys"},
      {"subject":"ENA","cnum":8,"name":"Puhu ja ymmärrä paremmin"},
      {"subject":"ENA","cnum":9,"name":"Englannin nollakurssi"},
      {"subject":"ET","cnum":1,"name":"Hyvä elämä"},
      {"subject":"ET","cnum":2,"name":"Maailmankuva"},
      {"subject":"ET","cnum":3,"name":"Yksilö ja yhteisö"},
      {"subject":"FI","cnum":1,"name":"Johdatus filosofiseen ajatteluun"},
      {"subject":"FI","cnum":2,"name":"Filosofinen etiikka"},
      {"subject":"FI","cnum":3,"name":"Tiedon ja todellisuuden filosofia"},
      {"subject":"FI","cnum":4,"name":"Yhteiskuntafilosofia"},
      {"subject":"FI","cnum":5,"name":"Ympäristöfilosofia"},
      {"subject":"FY","cnum":1,"name":"Fysiikka luonnontieteenä"},
      {"subject":"FY","cnum":2,"name":"Lämpö"},
      {"subject":"FY","cnum":3,"name":"Aallot"},
      {"subject":"FY","cnum":4,"name":"Liikkeen lait"},
      {"subject":"FY","cnum":5,"name":"Pyöriminen ja gravitaatio"},
      {"subject":"FY","cnum":6,"name":"Sähkö"},
      {"subject":"FY","cnum":7,"name":"Sähkömagnetismi"},
      {"subject":"FY","cnum":8,"name":"Aine ja säteily"},
      {"subject":"GE","cnum":1,"name":"Sininen planeetta"},
      {"subject":"GE","cnum":2,"name":"Yhteinen maailma"},
      {"subject":"GE","cnum":3,"name":"Riskien maailma"},
      {"subject":"GE","cnum":4,"name":"Aluetutkimus"},
      {"subject":"GE","cnum":5,"name":"Globaalit kehityskysymykset"},
      {"subject":"HI","cnum":1,"name":"Eurooppalainen ihminen"},
      {"subject":"HI","cnum":2,"name":"Kansainväliset suhteet"},
      {"subject":"HI","cnum":3,"name":"Suomen historian käännekohtia"},
      {"subject":"HI","cnum":4,"name":"Ihminen, ympäristö ja kulttuuri"},
      {"subject":"HI","cnum":5,"name":"Suomen vaiheet esihistoriasta autonomian aikaan"},
      {"subject":"HI","cnum":6,"name":"Kulttuurien kohtaaminen"},
      {"subject":"HI","cnum":7,"name":"Mikrohistoria"},
      {"subject":"IAB3","cnum":1,"name":"Hyvää päivää, hauska tutustua"},
      {"subject":"IAB3","cnum":2,"name":"Näin asiat hoituvat"},
      {"subject":"IAB3","cnum":3,"name":"Vapaa-aika ja harrastukset"},
      {"subject":"IAB3","cnum":4,"name":"Meillä ja muualla"},
      {"subject":"IAB3","cnum":5,"name":"Ennen ja nyt"},
      {"subject":"IAB3","cnum":6,"name":"Opiskelu ja tulevaisuudensuunnitelmat"},
      {"subject":"KE","cnum":1,"name":"Ihmisen ja elinympäristön kemia"},
      {"subject":"KE","cnum":2,"name":"Kemian mikromaailma"},
      {"subject":"KE","cnum":3,"name":"Reaktiot ja energia"},
      {"subject":"KE","cnum":4,"name":"Metallit ja materiaalit"},
      {"subject":"KE","cnum":5,"name":"Reaktiot ja tasapaino"},
      {"subject":"KU","cnum":1,"name":"Minä, kuva ja kulttuuri"},
      {"subject":"KU","cnum":2,"name":"Ympäristö, paikka ja tila"},
      {"subject":"LI","cnum":1,"name":"Kuntokurssi"},
      {"subject":"LI","cnum":2,"name":"Palloilu"},
      {"subject":"LI","cnum":3,"name":"Talviliikunta"},
      {"subject":"LI","cnum":4,"name":"Luontoseikkailu"},
      {"subject":"MAA","cnum":1,"name":"Funktiot ja yhtälöt"},
      {"subject":"MAA","cnum":2,"name":"Polynomifunktiot"},
      {"subject":"MAA","cnum":3,"name":"Geometria"},
      {"subject":"MAA","cnum":4,"name":"Analyyttinen geometria"},
      {"subject":"MAA","cnum":5,"name":"Vektorit"},
      {"subject":"MAA","cnum":6,"name":"Todennäköisyys ja tilastot"},
      {"subject":"MAA","cnum":7,"name":"Derivaatta"},
      {"subject":"MAA","cnum":8,"name":"Juuri- ja logaritmifunktiot"},
      {"subject":"MAA","cnum":9,"name":"Trigonometriset funktiot ja lukujonot"},
      {"subject":"MAA","cnum":10,"name":"Integraalilaskenta"},
      {"subject":"MAA","cnum":11,"name":"Lukuteoria ja logiikka"},
      {"subject":"MAA","cnum":12,"name":"Numeerisia ja algebrallisia menetelmiä"},
      {"subject":"MAA","cnum":13,"name":"Differentiaali- ja integraalilaskennan jatkokurssi"},
      {"subject":"MAB","cnum":1,"name":"Lausekkeet ja yhtälöt"},
      {"subject":"MAB","cnum":2,"name":"Geometria"},
      {"subject":"MAB","cnum":3,"name":"Matemaattisia malleja I"},
      {"subject":"MAB","cnum":4,"name":"Matemaattinen analyysi"},
      {"subject":"MAB","cnum":5,"name":"Tilastot ja todennäköisyys"},
      {"subject":"MAB","cnum":6,"name":"Matemaattisia malleja II"},
      {"subject":"MAB","cnum":7,"name":"Talousmatematiikka"},
      {"subject":"MAB","cnum":8,"name":"Matemaattisia malleja III"},
      {"subject":"ME","cnum":1,"name":"Median maailma"},
      {"subject":"ME","cnum":2,"name":"Median tulkinta"},
      {"subject":"ME","cnum":3,"name":"Sisältöä mediaan 1"},
      {"subject":"ME","cnum":4,"name":"Sisältöä mediaan 2"},
      {"subject":"ME","cnum":5,"name":"Lukiodiplomikurssi"},
      {"subject":"MU","cnum":1,"name":"Musiikki ja minä"},
      {"subject":"MU","cnum":2,"name":"Moniääninen Suomi"},
      {"subject":"OP","cnum":1,"name":"HOPS-kurssi"},
      {"subject":"OP","cnum":2,"name":"Abi-ohjaus"},
      {"subject":"OP","cnum":3,"name":"Tutorkurssi"},
      {"subject":"PS","cnum":1,"name":"Psyykkinen toiminta, oppiminen ja vuorovaikutus"},
      {"subject":"PS","cnum":2,"name":"Ihmisen psyykkinen kehitys"},
      {"subject":"PS","cnum":3,"name":"Ihmisen tiedonkäsittelyn perusteet"},
      {"subject":"PS","cnum":4,"name":"Motivaatio, tunteet ja älykäs toiminta"},
      {"subject":"PS","cnum":5,"name":"Persoonallisuus ja mielenterveys"},
      {"subject":"RAB3","cnum":1,"name":"Hyvää päivää, hauska tutustua"},
      {"subject":"RAB3","cnum":2,"name":"Näin asiat hoituvat"},
      {"subject":"RAB3","cnum":3,"name":"Vapaa-aika ja harrastukset"},
      {"subject":"RAB3","cnum":4,"name":"Meillä ja muualla"},
      {"subject":"RAB3","cnum":5,"name":"Ennen ja nyt"},
      {"subject":"RAB3","cnum":6,"name":"Opiskelu ja tulevaisuudensuunnitelmat"},
      {"subject":"RUB","cnum":1,"name":"Opiskelu ja vapaa-aika"},
      {"subject":"RUB","cnum":2,"name":"Arkielämää Pohjoismaissa"},
      {"subject":"RUB","cnum":3,"name":"Suomi, Pohjoismaat ja Eurooppa"},
      {"subject":"RUB","cnum":4,"name":"Elämää yhdessä ja erikseen"},
      {"subject":"RUB","cnum":5,"name":"Elinympäristömme"},
      {"subject":"RUB","cnum":7,"name":"Yhteinen maailma ja kansainvälistyminen"},
      {"subject":"RUB","cnum":8,"name":"Ruotsin nollakurssi"},
      {"subject":"RUB","cnum":9,"name":"Ruotsin abikurssi"},
      {"subject":"S2","cnum":1,"name":"Perusteet hallintaan"},
      {"subject":"S2","cnum":2,"name":"Kieli käyttöön"},
      {"subject":"S2","cnum":3,"name":"Kielellä vaikutetaan"},
      {"subject":"S2","cnum":4,"name":"Tekstitaidot kuntoon"},
      {"subject":"S2","cnum":5,"name":"Suomalainen kulttuuri tutuksi"},
      {"subject":"S2","cnum":6,"name":"Syvempi tekstin ymmärtäminen"},
      {"subject":"S2","cnum":7,"name":"Puhekieli tarkasteluun"},
      {"subject":"S2","cnum":8,"name":"Erilaisten tekstien kirjoittamista"},
      {"subject":"S2","cnum":9,"name":"Kirjallisuus tiedon ja ilon lähteenä"},
      {"subject":"SAB3","cnum":1,"name":"Hyvää päivää, hauska tutustua"},
      {"subject":"SAB3","cnum":2,"name":"Näin asiat hoituvat"},
      {"subject":"SAB3","cnum":3,"name":"Vapaa-aika ja harrastukset"},
      {"subject":"SAB3","cnum":4,"name":"Meillä ja muualla"},
      {"subject":"SAB3","cnum":5,"name":"Ennen ja nyt"},
      {"subject":"SAB3","cnum":6,"name":"Opiskelu ja tulevaisuudensuunnitelmat"},
      {"subject":"SAB3","cnum":7,"name":"Kulttuuri"},
      {"subject":"TE","cnum":1,"name":"Terveyden perusteet"},
      {"subject":"TE","cnum":2,"name":"Terveys ja arkielämä"},
      {"subject":"TE","cnum":3,"name":"Terveys ja tutkimus"},
      {"subject":"UE","cnum":1,"name":"Uskonnon luonne ja merkitys"},
      {"subject":"UE","cnum":2,"name":"Kirkko, kulttuuri ja yhteiskunta"},
      {"subject":"UE","cnum":3,"name":"Ihmisen elämä ja etiikka"},
      {"subject":"UE","cnum":4,"name":"Uskontojen maailmat"},
      {"subject":"UE","cnum":5,"name":"Mihin suomalainen uskoo?"},
      {"subject":"UO","cnum":1,"name":"Ortodoksinen maailma"},
      {"subject":"YH","cnum":1,"name":"Yhteiskuntatieto"},
      {"subject":"YH","cnum":2,"name":"Taloustieto"},
      {"subject":"YH","cnum":3,"name":"Kansalaisen lakitieto"},
      {"subject":"YH","cnum":4,"name":"Eurooppalaisuus ja Euroopan unioni"},
      {"subject":"AI","cnum":1,"name":"Tekstien rakenteita ja merkityksiä"},
      {"subject":"AI","cnum":2,"name":"Kirjallisuuden keinoja ja tulkintaa"},
      {"subject":"AI","cnum":3,"name":"Tekstit ja vaikuttaminen"},
      {"subject":"AI","cnum":4,"name":"Teksti, tyyli ja konteksti"},
      {"subject":"AI","cnum":5,"name":"Kieli, kirjallisuus ja identiteetti"},
      {"subject":"AI","cnum":6,"name":"Tekstitaitojen syventäminen"},
      {"subject":"AI","cnum":7,"name":"Puheviestinnän taitojen syventäminen"},
      {"subject":"AI","cnum":8,"name":"Kieli, tekstit ja vuorovaikutus"},
      {"subject":"AI","cnum":9,"name":"Kirjoittaminen ja nykykulttuuri"},
      {"subject":"AI","cnum":10,"name":"Kieli huoltoon"},
      {"subject":"PS","cnum":6,"name":"Sosiaali- ja mediapsykologia"},
      {"subject":"AI","cnum":11,"name":"Kaunokirjallisuuden syventävä kurssi"},
      {"subject":"ENA","cnum":10,"name":"Englannin sanastokurssi"},
      {"subject":"ENA","cnum":11,"name":"Pressienglanti"},
      {"subject":"RUB","cnum":6,"name":"Kulttuurin tekijöitä ja näkijöitä"},
      {"subject":"RUB","cnum":10,"name":"Kulttuurin tekijöitä ja näkijöitä"},
      {"subject":"MAB","cnum":10,"name":"Tilastomatematiikan syventävä kurssi"},
      {"subject":"MAB","cnum":9,"name":"Matematiikan nollakurssi"},
      {"subject":"MAB","cnum":11,"name":"Matematiikan abikurssi"},
      {"subject":"MAA","cnum":15,"name":"Pitkän matematiikan nollakurssi"},
      {"subject":"MAA","cnum":14,"name":"Pitkän matematiikan abikurssi"}
    ];
    
		for (var i = 0; i < data.length;i++) {
		  var module = data[i];
		  
      if (api.modules.listIdsBySubjectCodeAndCourseNumber(module.subject, module.cnum).length == 0) {
        api.modules.create(module.name, "Moduli kurssille '" + module.name + "'", Math.round((Math.random() * 20) + 10), module.subject, module.cnum);
      } else {
        api.log("Module for " + module.subject + "/" + module.cnum + " already exists");
      }
		}	
	}
})