package fi.otavanopisto.pyramus.koski.koodisto;

import fi.otavanopisto.pyramus.koski.KoodistoEnum;

@KoodistoEnum("aikuistenperusopetuksenalkuvaiheenkurssit2017")
public enum AikuistenPerusopetuksenAlkuvaiheenKurssit2017 {

  A_X_A1              ("A(X)A1"),
  AEAA1               ("AEAA1"),
  AEAA2               ("AEAA2"),
  AEAA3               ("AEAA3"),
  AEAA4               ("AEAA4"),
  AENA1               ("AENA1"),
  AENA2               ("AENA2"),
  AENA3               ("AENA3"),
  AENA4               ("AENA4"),
  AIAA1               ("AIAA1"),
  AIAA2               ("AIAA2"),
  AIAA3               ("AIAA3"),
  AIAA4               ("AIAA4"),
  AKXA1               ("AKXA1"),
  AKXA2               ("AKXA2"),
  AKXA3               ("AKXA3"),
  AKXA4               ("AKXA4"),
  ALAA1               ("ALAA1"),
  ALAA2               ("ALAA2"),
  ALAA3               ("ALAA3"),
  ALAA4               ("ALAA4"),
  AMA1                ("AMA1"),
  AMA2                ("AMA2"),
  AMA3                ("AMA3"),
  AMA4                ("AMA4"),
  AMA5                ("AMA5"),
  AOT1                ("AOT1"),
  AOT2                ("AOT2"),
  APOA1               ("APOA1"),
  APOA2               ("APOA2"),
  APOA3               ("APOA3"),
  APOA4               ("APOA4"),
  ARAA1               ("ARAA1"),
  ARAA2               ("ARAA2"),
  ARAA3               ("ARAA3"),
  ARAA4               ("ARAA4"),
  AS21                ("AS21"),
  AS210               ("AS210"),
  AS211               ("AS211"),
  AS212               ("AS212"),
  AS213               ("AS213"),
  AS214               ("AS214"),
  AS215               ("AS215"),
  AS216               ("AS216"),
  AS217               ("AS217"),
  AS22                ("AS22"),
  AS23                ("AS23"),
  AS24                ("AS24"),
  AS25                ("AS25"),
  AS26                ("AS26"),
  AS27                ("AS27"),
  AS28                ("AS28"),
  AS29                ("AS29"),
  ASAA1               ("ASAA1"),
  ASAA2               ("ASAA2"),
  ASAA3               ("ASAA3"),
  ASAA4               ("ASAA4"),
  ASMA1               ("ASMA1"),
  ASMA2               ("ASMA2"),
  ASMA3               ("ASMA3"),
  ASMA4               ("ASMA4"),
  ATE1                ("ATE1"),
  AVEA1               ("AVEA1"),
  AVEA2               ("AVEA2"),
  AVEA3               ("AVEA3"),
  AVEA4               ("AVEA4"),
  AYK1                ("AYK1"),
  AYK2                ("AYK2"),
  AYK3                ("AYK3"),
  AYL1                ("AYL1"),
  AYL2                ("AYL2"),
  AÄI1                ("AÄI1"),
  AÄI10               ("AÄI10"),
  AÄI11               ("AÄI11"),
  AÄI12               ("AÄI12"),
  AÄI13               ("AÄI13"),
  AÄI14               ("AÄI14"),
  AÄI15               ("AÄI15"),
  AÄI16               ("AÄI16"),
  AÄI17               ("AÄI17"),
  AÄI2                ("AÄI2"),
  AÄI3                ("AÄI3"),
  AÄI4                ("AÄI4"),
  AÄI5                ("AÄI5"),
  AÄI6                ("AÄI6"),
  AÄI7                ("AÄI7"),
  AÄI8                ("AÄI8"),
  AÄI9                ("AÄI9"),
  LMA1                ("LMA1"),
  LMA2                ("LMA2"),
  LMA3                ("LMA3"),
  LOT1                ("LOT1"),
  LOT2                ("LOT2"),
  LYK1                ("LYK1"),
  LYK2                ("LYK2"),
  LYL1                ("LYL1"),
  LÄI1                ("LÄI1"),
  LÄI10               ("LÄI10"),
  LÄI11               ("LÄI11"),
  LÄI12               ("LÄI12"),
  LÄI13               ("LÄI13"),
  LÄI14               ("LÄI14"),
  LÄI15               ("LÄI15"),
  LÄI2                ("LÄI2"),
  LÄI3                ("LÄI3"),
  LÄI4                ("LÄI4"),
  LÄI5                ("LÄI5"),
  LÄI6                ("LÄI6"),
  LÄI7                ("LÄI7"),
  LÄI8                ("LÄI8"),
  LÄI9                ("LÄI9");

  AikuistenPerusopetuksenAlkuvaiheenKurssit2017(String value) {
    this.value = value;
  }
  
  @Override
  public String toString() {
    return value;
  }
  
  private String value;
}
