package fi.otavanopisto.pyramus.koski.koodisto;

import fi.otavanopisto.pyramus.koski.KoodistoEnum;

@KoodistoEnum("suorituksentyyppi")
public enum SuorituksenTyyppi {
  aikuistenperusopetuksenalkuvaiheenkurssi,
  aikuistenperusopetuksenalkuvaiheenoppiaine,
  aikuistenperusopetuksenkurssi,
  aikuistenperusopetuksenoppiaine,
  aikuistenperusopetuksenoppimaara,
  aikuistenperusopetuksenoppimaaranalkuvaihe,
  ammatillinentutkinto,
  ammatillinentutkintoosittainen,
  ammatillisentutkinnonosa,
  ammatillisentutkinnonosaapienempikokonaisuus,
  ammatillisentutkinnonosanosaalue,
  esiopetuksensuoritus,
  ibkurssi,
  iboppiaine,
  iboppiainecas,
  iboppiaineee,
  iboppiainetok,
  ibtutkinto,
  korkeakoulunopintojakso,
  korkeakoulututkinto,
  lukionkurssi,
  lukionmuuopinto,
  lukionoppiaine,
  lukionoppiaineenoppimaara,
  lukionoppimaara,
  luva,
  luvakurssi,
  luvalukionoppiaine,
  luvaoppiaine,
  muuperusopetuksenlisaopetuksensuoritus,
  nayttotutkintoonvalmistavakoulutus,
  nayttotutkintoonvalmistavankoulutuksenosa,
  perusopetukseenvalmistavanopetuksenoppiaine,
  perusopetukseenvalmistavaopetus,
  perusopetuksenlisaopetuksenoppiaine,
  perusopetuksenlisaopetuksentoimintaalue,
  perusopetuksenlisaopetus,
  perusopetuksenoppiaine,
  perusopetuksenoppiaineenoppimaara,
  perusopetuksenoppimaara,
  perusopetuksentoimintaalue,
  perusopetuksenvuosiluokka,
  preibkurssi,
  preiboppiaine,
  preiboppimaara,
  telma,
  telmakoulutuksenosa,
  valma,
  valmakoulutuksenosa,
  ylioppilastutkinnonkoe,
  ylioppilastutkinto
}
