package fi.otavanopisto.pyramus.domainmodel.koski;

public enum KoskiPersonState {

  PENDING,
  SUCCESS,
  SERVER_FAILURE,
  SERVER_UNAVAILABLE,
  UNKNOWN_FAILURE, 
  NO_CURRICULUM,
  NO_UNIQUE_ID,
  NO_RESOLVABLE_SUBJECTS,
  LINKED_MISSING_VALUES,
  UNKNOWN_LANGUAGE,
  UNRESOLVED_CREDIT_CURRICULUM,
  UNREPORTED_CREDIT,
  UNRESOLVABLE_SUBTYPES,
  MISSING_STUDYAPPROVER,
  MISSING_STUDYAPPROVEDATE,
  MISSING_STUDYENDREASONMAPPING,
  NO_STUDYSTARTDATE,
  EXISTING_INTERNETIX_STUDYPERMIT_WITHOUT_CREDITS,
  CONFLICTING_COURSELENGTH,
  GENERIC_WARNING,
  GENERIC_ERROR,
  INTERNETIX_BOTH_LINES;
  
  /* Pending states */
  public static KoskiPersonState[] PENDING_STATES = { PENDING };
  /* Success states */
  public static KoskiPersonState[] SUCCESS_STATES = { SUCCESS };
  /* Warning states which indicate succeeded update but with warnings */
  public static KoskiPersonState[] WARNING_STATES = { GENERIC_WARNING, LINKED_MISSING_VALUES, NO_RESOLVABLE_SUBJECTS, UNKNOWN_LANGUAGE, 
      UNRESOLVED_CREDIT_CURRICULUM, UNREPORTED_CREDIT, UNRESOLVABLE_SUBTYPES, MISSING_STUDYENDREASONMAPPING };
  /* Error states which prevent the update altogether */
  public static KoskiPersonState[] ERROR_STATES = { GENERIC_ERROR, SERVER_FAILURE, SERVER_UNAVAILABLE, UNKNOWN_FAILURE, NO_CURRICULUM, INTERNETIX_BOTH_LINES,
      NO_UNIQUE_ID, MISSING_STUDYAPPROVER, MISSING_STUDYAPPROVEDATE, NO_STUDYSTARTDATE, EXISTING_INTERNETIX_STUDYPERMIT_WITHOUT_CREDITS, CONFLICTING_COURSELENGTH };
}
