package fi.pyramus.rest.tranquil;

public class BaseLookup implements fi.tranquil.processing.EntityLookup {

  public BaseLookup() {
    classes.put(fi.pyramus.domainmodel.reports.ReportCategory.class, fi.pyramus.rest.tranquil.reports.ReportCategoryBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentStudyEndReason.class, fi.pyramus.rest.tranquil.students.StudentStudyEndReasonBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentVariableKey.class, fi.pyramus.rest.tranquil.students.StudentVariableKeyBase.class);
    classes.put(fi.pyramus.domainmodel.grading.TransferCredit.class, fi.pyramus.rest.tranquil.grading.TransferCreditBase.class);
    classes.put(fi.pyramus.domainmodel.base.School.class, fi.pyramus.rest.tranquil.base.SchoolBase.class);
    classes.put(fi.pyramus.domainmodel.base.BillingDetails.class, fi.pyramus.rest.tranquil.base.BillingDetailsBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseDescription.class, fi.pyramus.rest.tranquil.courses.CourseDescriptionBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentContactLogEntryComment.class, fi.pyramus.rest.tranquil.students.StudentContactLogEntryCommentBase.class);
    classes.put(fi.pyramus.domainmodel.resources.WorkResource.class, fi.pyramus.rest.tranquil.resources.WorkResourceBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentContactLogEntry.class, fi.pyramus.rest.tranquil.students.StudentContactLogEntryBase.class);
    classes.put(fi.pyramus.domainmodel.users.UserVariableKey.class, fi.pyramus.rest.tranquil.users.UserVariableKeyBase.class);
    classes.put(fi.pyramus.domainmodel.base.ContactInfo.class, fi.pyramus.rest.tranquil.base.ContactInfoBase.class);
    classes.put(fi.pyramus.domainmodel.projects.StudentProjectModule.class, fi.pyramus.rest.tranquil.projects.StudentProjectModuleBase.class);
    classes.put(fi.pyramus.domainmodel.grading.CreditVariableKey.class, fi.pyramus.rest.tranquil.grading.CreditVariableKeyBase.class);
    classes.put(fi.pyramus.domainmodel.help.HelpPage.class, fi.pyramus.rest.tranquil.help.HelpPageBase.class);
    classes.put(fi.pyramus.domainmodel.reports.ReportContext.class, fi.pyramus.rest.tranquil.reports.ReportContextBase.class);
    classes.put(fi.pyramus.domainmodel.help.HelpPageContent.class, fi.pyramus.rest.tranquil.help.HelpPageContentBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentVariable.class, fi.pyramus.rest.tranquil.students.StudentVariableBase.class);
    classes.put(fi.pyramus.domainmodel.base.Nationality.class, fi.pyramus.rest.tranquil.base.NationalityBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseUser.class, fi.pyramus.rest.tranquil.courses.CourseUserBase.class);
    classes.put(fi.pyramus.domainmodel.grading.CourseAssessmentRequest.class, fi.pyramus.rest.tranquil.grading.CourseAssessmentRequestBase.class);
    classes.put(fi.pyramus.domainmodel.file.File.class, fi.pyramus.rest.tranquil.file.FileBase.class);
    classes.put(fi.pyramus.domainmodel.system.Setting.class, fi.pyramus.rest.tranquil.system.SettingBase.class);
    classes.put(fi.pyramus.domainmodel.base.Tag.class, fi.pyramus.rest.tranquil.base.TagBase.class);
    classes.put(fi.pyramus.domainmodel.base.CourseBaseVariable.class, fi.pyramus.rest.tranquil.base.CourseBaseVariableBase.class);
    classes.put(fi.pyramus.domainmodel.projects.Project.class, fi.pyramus.rest.tranquil.projects.ProjectBase.class);
    classes.put(fi.pyramus.domainmodel.resources.Resource.class, fi.pyramus.rest.tranquil.resources.ResourceBase.class);
    classes.put(fi.pyramus.domainmodel.system.SettingKey.class, fi.pyramus.rest.tranquil.system.SettingKeyBase.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntryEntityProperty.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryEntityPropertyBase.class);
    classes.put(fi.pyramus.domainmodel.base.ComponentBase.class, fi.pyramus.rest.tranquil.base.ComponentBaseBase.class);
    classes.put(fi.pyramus.domainmodel.resources.MaterialResource.class, fi.pyramus.rest.tranquil.resources.MaterialResourceBase.class);
    classes.put(fi.pyramus.domainmodel.base.StudyProgrammeCategory.class, fi.pyramus.rest.tranquil.base.StudyProgrammeCategoryBase.class);
    classes.put(fi.pyramus.domainmodel.base.EducationType.class, fi.pyramus.rest.tranquil.base.EducationTypeBase.class);
    classes.put(fi.pyramus.domainmodel.base.ContactURL.class, fi.pyramus.rest.tranquil.base.ContactURLBase.class);
    classes.put(fi.pyramus.domainmodel.base.Address.class, fi.pyramus.rest.tranquil.base.AddressBase.class);
    classes.put(fi.pyramus.domainmodel.users.InternalAuth.class, fi.pyramus.rest.tranquil.users.InternalAuthBase.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntryEntity.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryEntityBase.class);
    classes.put(fi.pyramus.domainmodel.grading.ProjectAssessment.class, fi.pyramus.rest.tranquil.grading.ProjectAssessmentBase.class);
    classes.put(fi.pyramus.domainmodel.grading.GradingScale.class, fi.pyramus.rest.tranquil.grading.GradingScaleBase.class);
    classes.put(fi.pyramus.domainmodel.base.MagicKey.class, fi.pyramus.rest.tranquil.base.MagicKeyBase.class);
    classes.put(fi.pyramus.domainmodel.base.SchoolVariable.class, fi.pyramus.rest.tranquil.base.SchoolVariableBase.class);
    classes.put(fi.pyramus.domainmodel.projects.ProjectModule.class, fi.pyramus.rest.tranquil.projects.ProjectModuleBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseComponentResource.class, fi.pyramus.rest.tranquil.courses.CourseComponentResourceBase.class);
    classes.put(fi.pyramus.domainmodel.users.User.class, fi.pyramus.rest.tranquil.users.UserBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseEnrolmentType.class, fi.pyramus.rest.tranquil.courses.CourseEnrolmentTypeBase.class);
    classes.put(fi.pyramus.domainmodel.base.ContactURLType.class, fi.pyramus.rest.tranquil.base.ContactURLTypeBase.class);
    classes.put(fi.pyramus.domainmodel.modules.Module.class, fi.pyramus.rest.tranquil.modules.ModuleBase.class);
    classes.put(fi.pyramus.domainmodel.users.UserVariable.class, fi.pyramus.rest.tranquil.users.UserVariableBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentGroup.class, fi.pyramus.rest.tranquil.students.StudentGroupBase.class);
    classes.put(fi.pyramus.domainmodel.base.AcademicTerm.class, fi.pyramus.rest.tranquil.base.AcademicTermBase.class);
    classes.put(fi.pyramus.domainmodel.courses.GradeCourseResource.class, fi.pyramus.rest.tranquil.courses.GradeCourseResourceBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseComponent.class, fi.pyramus.rest.tranquil.courses.CourseComponentBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseParticipationType.class, fi.pyramus.rest.tranquil.courses.CourseParticipationTypeBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentGroupUser.class, fi.pyramus.rest.tranquil.students.StudentGroupUserBase.class);
    classes.put(fi.pyramus.domainmodel.help.HelpFolder.class, fi.pyramus.rest.tranquil.help.HelpFolderBase.class);
    classes.put(fi.pyramus.domainmodel.courses.Course.class, fi.pyramus.rest.tranquil.courses.CourseBase.class);
    classes.put(fi.pyramus.domainmodel.reports.Report.class, fi.pyramus.rest.tranquil.reports.ReportBase.class);
    classes.put(fi.pyramus.domainmodel.help.HelpItemTitle.class, fi.pyramus.rest.tranquil.help.HelpItemTitleBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseDescriptionCategory.class, fi.pyramus.rest.tranquil.courses.CourseDescriptionCategoryBase.class);
    classes.put(fi.pyramus.domainmodel.changelog.TrackedEntityProperty.class, fi.pyramus.rest.tranquil.changelog.TrackedEntityPropertyBase.class);
    classes.put(fi.pyramus.domainmodel.base.SchoolVariableKey.class, fi.pyramus.rest.tranquil.base.SchoolVariableKeyBase.class);
    classes.put(fi.pyramus.domainmodel.grading.CreditVariable.class, fi.pyramus.rest.tranquil.grading.CreditVariableBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentEducationalLevel.class, fi.pyramus.rest.tranquil.students.StudentEducationalLevelBase.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntryProperty.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryPropertyBase.class);
    classes.put(fi.pyramus.domainmodel.file.FileType.class, fi.pyramus.rest.tranquil.file.FileTypeBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentExaminationType.class, fi.pyramus.rest.tranquil.students.StudentExaminationTypeBase.class);
    classes.put(fi.pyramus.domainmodel.modules.ModuleComponent.class, fi.pyramus.rest.tranquil.modules.ModuleComponentBase.class);
    classes.put(fi.pyramus.domainmodel.courses.OtherCost.class, fi.pyramus.rest.tranquil.courses.OtherCostBase.class);
    classes.put(fi.pyramus.domainmodel.plugins.PluginRepository.class, fi.pyramus.rest.tranquil.plugins.PluginRepositoryBase.class);
    classes.put(fi.pyramus.domainmodel.base.EducationSubtype.class, fi.pyramus.rest.tranquil.base.EducationSubtypeBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseUserRole.class, fi.pyramus.rest.tranquil.courses.CourseUserRoleBase.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntry.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryBase.class);
    classes.put(fi.pyramus.domainmodel.grading.CreditLink.class, fi.pyramus.rest.tranquil.grading.CreditLinkBase.class);
    classes.put(fi.pyramus.domainmodel.plugins.Plugin.class, fi.pyramus.rest.tranquil.plugins.PluginBase.class);
    classes.put(fi.pyramus.domainmodel.base.CourseEducationSubtype.class, fi.pyramus.rest.tranquil.base.CourseEducationSubtypeBase.class);
    classes.put(fi.pyramus.domainmodel.base.PhoneNumber.class, fi.pyramus.rest.tranquil.base.PhoneNumberBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentActivityType.class, fi.pyramus.rest.tranquil.students.StudentActivityTypeBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseState.class, fi.pyramus.rest.tranquil.courses.CourseStateBase.class);
    classes.put(fi.pyramus.domainmodel.students.Student.class, fi.pyramus.rest.tranquil.students.StudentBase.class);
    classes.put(fi.pyramus.domainmodel.base.StudyProgramme.class, fi.pyramus.rest.tranquil.base.StudyProgrammeBase.class);
    classes.put(fi.pyramus.domainmodel.resources.ResourceCategory.class, fi.pyramus.rest.tranquil.resources.ResourceCategoryBase.class);
    classes.put(fi.pyramus.domainmodel.courses.StudentCourseResource.class, fi.pyramus.rest.tranquil.courses.StudentCourseResourceBase.class);
    classes.put(fi.pyramus.domainmodel.base.Defaults.class, fi.pyramus.rest.tranquil.base.DefaultsBase.class);
    classes.put(fi.pyramus.domainmodel.base.Language.class, fi.pyramus.rest.tranquil.base.LanguageBase.class);
    classes.put(fi.pyramus.domainmodel.base.CourseEducationType.class, fi.pyramus.rest.tranquil.base.CourseEducationTypeBase.class);
    classes.put(fi.pyramus.domainmodel.base.Municipality.class, fi.pyramus.rest.tranquil.base.MunicipalityBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseStudent.class, fi.pyramus.rest.tranquil.courses.CourseStudentBase.class);
    classes.put(fi.pyramus.domainmodel.grading.TransferCreditTemplateCourse.class, fi.pyramus.rest.tranquil.grading.TransferCreditTemplateCourseBase.class);
    classes.put(fi.pyramus.domainmodel.base.CourseBaseVariableKey.class, fi.pyramus.rest.tranquil.base.CourseBaseVariableKeyBase.class);
    classes.put(fi.pyramus.domainmodel.drafts.FormDraft.class, fi.pyramus.rest.tranquil.drafts.FormDraftBase.class);
    classes.put(fi.pyramus.domainmodel.help.HelpItem.class, fi.pyramus.rest.tranquil.help.HelpItemBase.class);
    classes.put(fi.pyramus.domainmodel.base.CourseBase.class, fi.pyramus.rest.tranquil.base.CourseBaseBase.class);
    classes.put(fi.pyramus.domainmodel.students.AbstractStudent.class, fi.pyramus.rest.tranquil.students.AbstractStudentBase.class);
    classes.put(fi.pyramus.domainmodel.courses.BasicCourseResource.class, fi.pyramus.rest.tranquil.courses.BasicCourseResourceBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseStudentVariable.class, fi.pyramus.rest.tranquil.courses.CourseStudentVariableBase.class);
    classes.put(fi.pyramus.domainmodel.projects.StudentProject.class, fi.pyramus.rest.tranquil.projects.StudentProjectBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentGroupStudent.class, fi.pyramus.rest.tranquil.students.StudentGroupStudentBase.class);
    classes.put(fi.pyramus.domainmodel.base.EducationalTimeUnit.class, fi.pyramus.rest.tranquil.base.EducationalTimeUnitBase.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseStudentVariableKey.class, fi.pyramus.rest.tranquil.courses.CourseStudentVariableKeyBase.class);
    classes.put(fi.pyramus.domainmodel.base.ContactType.class, fi.pyramus.rest.tranquil.base.ContactTypeBase.class);
    classes.put(fi.pyramus.domainmodel.base.Email.class, fi.pyramus.rest.tranquil.base.EmailBase.class);
    classes.put(fi.pyramus.domainmodel.grading.Credit.class, fi.pyramus.rest.tranquil.grading.CreditBase.class);
    classes.put(fi.pyramus.domainmodel.grading.Grade.class, fi.pyramus.rest.tranquil.grading.GradeBase.class);
    classes.put(fi.pyramus.domainmodel.file.StudentFile.class, fi.pyramus.rest.tranquil.file.StudentFileBase.class);
    classes.put(fi.pyramus.domainmodel.students.StudentImage.class, fi.pyramus.rest.tranquil.students.StudentImageBase.class);
    classes.put(fi.pyramus.domainmodel.base.EducationalLength.class, fi.pyramus.rest.tranquil.base.EducationalLengthBase.class);
    classes.put(fi.pyramus.domainmodel.grading.TransferCreditTemplate.class, fi.pyramus.rest.tranquil.grading.TransferCreditTemplateBase.class);
    classes.put(fi.pyramus.domainmodel.grading.CourseAssessment.class, fi.pyramus.rest.tranquil.grading.CourseAssessmentBase.class);
    classes.put(fi.pyramus.domainmodel.base.Subject.class, fi.pyramus.rest.tranquil.base.SubjectBase.class);
    classes.put(fi.pyramus.domainmodel.base.SchoolField.class, fi.pyramus.rest.tranquil.base.SchoolFieldBase.class);
  }

  @Override
  public Class<?> findTranquilModel(Class<?> entity) {
    return classes.get(entity);
  }

  private java.util.Map<Class<?>, Class<?>> classes =  new java.util.HashMap<Class<?>, Class<?>>();
}
