package fi.pyramus.rest.tranquil;

public class CompleteLookup implements fi.tranquil.processing.EntityLookup {

  public CompleteLookup() {
    classes.put(fi.pyramus.domainmodel.reports.ReportCategory.class, fi.pyramus.rest.tranquil.reports.ReportCategoryComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentStudyEndReason.class, fi.pyramus.rest.tranquil.students.StudentStudyEndReasonComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentVariableKey.class, fi.pyramus.rest.tranquil.students.StudentVariableKeyComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.TransferCredit.class, fi.pyramus.rest.tranquil.grading.TransferCreditComplete.class);
    classes.put(fi.pyramus.domainmodel.base.School.class, fi.pyramus.rest.tranquil.base.SchoolComplete.class);
    classes.put(fi.pyramus.domainmodel.base.BillingDetails.class, fi.pyramus.rest.tranquil.base.BillingDetailsComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseDescription.class, fi.pyramus.rest.tranquil.courses.CourseDescriptionComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentContactLogEntryComment.class, fi.pyramus.rest.tranquil.students.StudentContactLogEntryCommentComplete.class);
    classes.put(fi.pyramus.domainmodel.resources.WorkResource.class, fi.pyramus.rest.tranquil.resources.WorkResourceComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentContactLogEntry.class, fi.pyramus.rest.tranquil.students.StudentContactLogEntryComplete.class);
    classes.put(fi.pyramus.domainmodel.users.UserVariableKey.class, fi.pyramus.rest.tranquil.users.UserVariableKeyComplete.class);
    classes.put(fi.pyramus.domainmodel.base.ContactInfo.class, fi.pyramus.rest.tranquil.base.ContactInfoComplete.class);
    classes.put(fi.pyramus.domainmodel.projects.StudentProjectModule.class, fi.pyramus.rest.tranquil.projects.StudentProjectModuleComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.CreditVariableKey.class, fi.pyramus.rest.tranquil.grading.CreditVariableKeyComplete.class);
    classes.put(fi.pyramus.domainmodel.help.HelpPage.class, fi.pyramus.rest.tranquil.help.HelpPageComplete.class);
    classes.put(fi.pyramus.domainmodel.reports.ReportContext.class, fi.pyramus.rest.tranquil.reports.ReportContextComplete.class);
    classes.put(fi.pyramus.domainmodel.help.HelpPageContent.class, fi.pyramus.rest.tranquil.help.HelpPageContentComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentVariable.class, fi.pyramus.rest.tranquil.students.StudentVariableComplete.class);
    classes.put(fi.pyramus.domainmodel.base.Nationality.class, fi.pyramus.rest.tranquil.base.NationalityComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseUser.class, fi.pyramus.rest.tranquil.courses.CourseUserComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.CourseAssessmentRequest.class, fi.pyramus.rest.tranquil.grading.CourseAssessmentRequestComplete.class);
    classes.put(fi.pyramus.domainmodel.file.File.class, fi.pyramus.rest.tranquil.file.FileComplete.class);
    classes.put(fi.pyramus.domainmodel.system.Setting.class, fi.pyramus.rest.tranquil.system.SettingComplete.class);
    classes.put(fi.pyramus.domainmodel.base.Tag.class, fi.pyramus.rest.tranquil.base.TagComplete.class);
    classes.put(fi.pyramus.domainmodel.base.CourseBaseVariable.class, fi.pyramus.rest.tranquil.base.CourseBaseVariableComplete.class);
    classes.put(fi.pyramus.domainmodel.projects.Project.class, fi.pyramus.rest.tranquil.projects.ProjectComplete.class);
    classes.put(fi.pyramus.domainmodel.resources.Resource.class, fi.pyramus.rest.tranquil.resources.ResourceComplete.class);
    classes.put(fi.pyramus.domainmodel.system.SettingKey.class, fi.pyramus.rest.tranquil.system.SettingKeyComplete.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntryEntityProperty.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryEntityPropertyComplete.class);
    classes.put(fi.pyramus.domainmodel.base.ComponentBase.class, fi.pyramus.rest.tranquil.base.ComponentBaseComplete.class);
    classes.put(fi.pyramus.domainmodel.resources.MaterialResource.class, fi.pyramus.rest.tranquil.resources.MaterialResourceComplete.class);
    classes.put(fi.pyramus.domainmodel.base.StudyProgrammeCategory.class, fi.pyramus.rest.tranquil.base.StudyProgrammeCategoryComplete.class);
    classes.put(fi.pyramus.domainmodel.base.EducationType.class, fi.pyramus.rest.tranquil.base.EducationTypeComplete.class);
    classes.put(fi.pyramus.domainmodel.base.ContactURL.class, fi.pyramus.rest.tranquil.base.ContactURLComplete.class);
    classes.put(fi.pyramus.domainmodel.base.Address.class, fi.pyramus.rest.tranquil.base.AddressComplete.class);
    classes.put(fi.pyramus.domainmodel.users.InternalAuth.class, fi.pyramus.rest.tranquil.users.InternalAuthComplete.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntryEntity.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryEntityComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.ProjectAssessment.class, fi.pyramus.rest.tranquil.grading.ProjectAssessmentComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.GradingScale.class, fi.pyramus.rest.tranquil.grading.GradingScaleComplete.class);
    classes.put(fi.pyramus.domainmodel.base.MagicKey.class, fi.pyramus.rest.tranquil.base.MagicKeyComplete.class);
    classes.put(fi.pyramus.domainmodel.base.SchoolVariable.class, fi.pyramus.rest.tranquil.base.SchoolVariableComplete.class);
    classes.put(fi.pyramus.domainmodel.projects.ProjectModule.class, fi.pyramus.rest.tranquil.projects.ProjectModuleComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseComponentResource.class, fi.pyramus.rest.tranquil.courses.CourseComponentResourceComplete.class);
    classes.put(fi.pyramus.domainmodel.users.User.class, fi.pyramus.rest.tranquil.users.UserComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseEnrolmentType.class, fi.pyramus.rest.tranquil.courses.CourseEnrolmentTypeComplete.class);
    classes.put(fi.pyramus.domainmodel.base.ContactURLType.class, fi.pyramus.rest.tranquil.base.ContactURLTypeComplete.class);
    classes.put(fi.pyramus.domainmodel.modules.Module.class, fi.pyramus.rest.tranquil.modules.ModuleComplete.class);
    classes.put(fi.pyramus.domainmodel.users.UserVariable.class, fi.pyramus.rest.tranquil.users.UserVariableComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentGroup.class, fi.pyramus.rest.tranquil.students.StudentGroupComplete.class);
    classes.put(fi.pyramus.domainmodel.base.AcademicTerm.class, fi.pyramus.rest.tranquil.base.AcademicTermComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.GradeCourseResource.class, fi.pyramus.rest.tranquil.courses.GradeCourseResourceComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseComponent.class, fi.pyramus.rest.tranquil.courses.CourseComponentComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseParticipationType.class, fi.pyramus.rest.tranquil.courses.CourseParticipationTypeComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentGroupUser.class, fi.pyramus.rest.tranquil.students.StudentGroupUserComplete.class);
    classes.put(fi.pyramus.domainmodel.help.HelpFolder.class, fi.pyramus.rest.tranquil.help.HelpFolderComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.Course.class, fi.pyramus.rest.tranquil.courses.CourseComplete.class);
    classes.put(fi.pyramus.domainmodel.reports.Report.class, fi.pyramus.rest.tranquil.reports.ReportComplete.class);
    classes.put(fi.pyramus.domainmodel.help.HelpItemTitle.class, fi.pyramus.rest.tranquil.help.HelpItemTitleComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseDescriptionCategory.class, fi.pyramus.rest.tranquil.courses.CourseDescriptionCategoryComplete.class);
    classes.put(fi.pyramus.domainmodel.changelog.TrackedEntityProperty.class, fi.pyramus.rest.tranquil.changelog.TrackedEntityPropertyComplete.class);
    classes.put(fi.pyramus.domainmodel.base.SchoolVariableKey.class, fi.pyramus.rest.tranquil.base.SchoolVariableKeyComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.CreditVariable.class, fi.pyramus.rest.tranquil.grading.CreditVariableComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentEducationalLevel.class, fi.pyramus.rest.tranquil.students.StudentEducationalLevelComplete.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntryProperty.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryPropertyComplete.class);
    classes.put(fi.pyramus.domainmodel.file.FileType.class, fi.pyramus.rest.tranquil.file.FileTypeComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentExaminationType.class, fi.pyramus.rest.tranquil.students.StudentExaminationTypeComplete.class);
    classes.put(fi.pyramus.domainmodel.modules.ModuleComponent.class, fi.pyramus.rest.tranquil.modules.ModuleComponentComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.OtherCost.class, fi.pyramus.rest.tranquil.courses.OtherCostComplete.class);
    classes.put(fi.pyramus.domainmodel.plugins.PluginRepository.class, fi.pyramus.rest.tranquil.plugins.PluginRepositoryComplete.class);
    classes.put(fi.pyramus.domainmodel.base.EducationSubtype.class, fi.pyramus.rest.tranquil.base.EducationSubtypeComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseUserRole.class, fi.pyramus.rest.tranquil.courses.CourseUserRoleComplete.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntry.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.CreditLink.class, fi.pyramus.rest.tranquil.grading.CreditLinkComplete.class);
    classes.put(fi.pyramus.domainmodel.plugins.Plugin.class, fi.pyramus.rest.tranquil.plugins.PluginComplete.class);
    classes.put(fi.pyramus.domainmodel.base.CourseEducationSubtype.class, fi.pyramus.rest.tranquil.base.CourseEducationSubtypeComplete.class);
    classes.put(fi.pyramus.domainmodel.base.PhoneNumber.class, fi.pyramus.rest.tranquil.base.PhoneNumberComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentActivityType.class, fi.pyramus.rest.tranquil.students.StudentActivityTypeComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseState.class, fi.pyramus.rest.tranquil.courses.CourseStateComplete.class);
    classes.put(fi.pyramus.domainmodel.students.Student.class, fi.pyramus.rest.tranquil.students.StudentComplete.class);
    classes.put(fi.pyramus.domainmodel.base.StudyProgramme.class, fi.pyramus.rest.tranquil.base.StudyProgrammeComplete.class);
    classes.put(fi.pyramus.domainmodel.resources.ResourceCategory.class, fi.pyramus.rest.tranquil.resources.ResourceCategoryComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.StudentCourseResource.class, fi.pyramus.rest.tranquil.courses.StudentCourseResourceComplete.class);
    classes.put(fi.pyramus.domainmodel.base.Defaults.class, fi.pyramus.rest.tranquil.base.DefaultsComplete.class);
    classes.put(fi.pyramus.domainmodel.base.Language.class, fi.pyramus.rest.tranquil.base.LanguageComplete.class);
    classes.put(fi.pyramus.domainmodel.base.CourseEducationType.class, fi.pyramus.rest.tranquil.base.CourseEducationTypeComplete.class);
    classes.put(fi.pyramus.domainmodel.base.Municipality.class, fi.pyramus.rest.tranquil.base.MunicipalityComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseStudent.class, fi.pyramus.rest.tranquil.courses.CourseStudentComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.TransferCreditTemplateCourse.class, fi.pyramus.rest.tranquil.grading.TransferCreditTemplateCourseComplete.class);
    classes.put(fi.pyramus.domainmodel.base.CourseBaseVariableKey.class, fi.pyramus.rest.tranquil.base.CourseBaseVariableKeyComplete.class);
    classes.put(fi.pyramus.domainmodel.drafts.FormDraft.class, fi.pyramus.rest.tranquil.drafts.FormDraftComplete.class);
    classes.put(fi.pyramus.domainmodel.help.HelpItem.class, fi.pyramus.rest.tranquil.help.HelpItemComplete.class);
    classes.put(fi.pyramus.domainmodel.base.CourseBase.class, fi.pyramus.rest.tranquil.base.CourseBaseComplete.class);
    classes.put(fi.pyramus.domainmodel.students.AbstractStudent.class, fi.pyramus.rest.tranquil.students.AbstractStudentComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.BasicCourseResource.class, fi.pyramus.rest.tranquil.courses.BasicCourseResourceComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseStudentVariable.class, fi.pyramus.rest.tranquil.courses.CourseStudentVariableComplete.class);
    classes.put(fi.pyramus.domainmodel.projects.StudentProject.class, fi.pyramus.rest.tranquil.projects.StudentProjectComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentGroupStudent.class, fi.pyramus.rest.tranquil.students.StudentGroupStudentComplete.class);
    classes.put(fi.pyramus.domainmodel.base.EducationalTimeUnit.class, fi.pyramus.rest.tranquil.base.EducationalTimeUnitComplete.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseStudentVariableKey.class, fi.pyramus.rest.tranquil.courses.CourseStudentVariableKeyComplete.class);
    classes.put(fi.pyramus.domainmodel.base.ContactType.class, fi.pyramus.rest.tranquil.base.ContactTypeComplete.class);
    classes.put(fi.pyramus.domainmodel.base.Email.class, fi.pyramus.rest.tranquil.base.EmailComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.Credit.class, fi.pyramus.rest.tranquil.grading.CreditComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.Grade.class, fi.pyramus.rest.tranquil.grading.GradeComplete.class);
    classes.put(fi.pyramus.domainmodel.file.StudentFile.class, fi.pyramus.rest.tranquil.file.StudentFileComplete.class);
    classes.put(fi.pyramus.domainmodel.students.StudentImage.class, fi.pyramus.rest.tranquil.students.StudentImageComplete.class);
    classes.put(fi.pyramus.domainmodel.base.EducationalLength.class, fi.pyramus.rest.tranquil.base.EducationalLengthComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.TransferCreditTemplate.class, fi.pyramus.rest.tranquil.grading.TransferCreditTemplateComplete.class);
    classes.put(fi.pyramus.domainmodel.grading.CourseAssessment.class, fi.pyramus.rest.tranquil.grading.CourseAssessmentComplete.class);
    classes.put(fi.pyramus.domainmodel.base.Subject.class, fi.pyramus.rest.tranquil.base.SubjectComplete.class);
    classes.put(fi.pyramus.domainmodel.base.SchoolField.class, fi.pyramus.rest.tranquil.base.SchoolFieldComplete.class);
  }

  @Override
  public Class<?> findTranquilModel(Class<?> entity) {
    return classes.get(entity);
  }

  private java.util.Map<Class<?>, Class<?>> classes =  new java.util.HashMap<Class<?>, Class<?>>();
}
