package fi.pyramus.rest.tranquil;

public class EntityLookup implements fi.tranquil.processing.EntityLookup {

  public EntityLookup() {
    classes.put(fi.pyramus.domainmodel.reports.ReportCategory.class, fi.pyramus.rest.tranquil.reports.ReportCategoryEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentStudyEndReason.class, fi.pyramus.rest.tranquil.students.StudentStudyEndReasonEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentVariableKey.class, fi.pyramus.rest.tranquil.students.StudentVariableKeyEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.TransferCredit.class, fi.pyramus.rest.tranquil.grading.TransferCreditEntity.class);
    classes.put(fi.pyramus.domainmodel.base.School.class, fi.pyramus.rest.tranquil.base.SchoolEntity.class);
    classes.put(fi.pyramus.domainmodel.base.BillingDetails.class, fi.pyramus.rest.tranquil.base.BillingDetailsEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseDescription.class, fi.pyramus.rest.tranquil.courses.CourseDescriptionEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentContactLogEntryComment.class, fi.pyramus.rest.tranquil.students.StudentContactLogEntryCommentEntity.class);
    classes.put(fi.pyramus.domainmodel.resources.WorkResource.class, fi.pyramus.rest.tranquil.resources.WorkResourceEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentContactLogEntry.class, fi.pyramus.rest.tranquil.students.StudentContactLogEntryEntity.class);
    classes.put(fi.pyramus.domainmodel.users.UserVariableKey.class, fi.pyramus.rest.tranquil.users.UserVariableKeyEntity.class);
    classes.put(fi.pyramus.domainmodel.base.ContactInfo.class, fi.pyramus.rest.tranquil.base.ContactInfoEntity.class);
    classes.put(fi.pyramus.domainmodel.projects.StudentProjectModule.class, fi.pyramus.rest.tranquil.projects.StudentProjectModuleEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.CreditVariableKey.class, fi.pyramus.rest.tranquil.grading.CreditVariableKeyEntity.class);
    classes.put(fi.pyramus.domainmodel.help.HelpPage.class, fi.pyramus.rest.tranquil.help.HelpPageEntity.class);
    classes.put(fi.pyramus.domainmodel.reports.ReportContext.class, fi.pyramus.rest.tranquil.reports.ReportContextEntity.class);
    classes.put(fi.pyramus.domainmodel.help.HelpPageContent.class, fi.pyramus.rest.tranquil.help.HelpPageContentEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentVariable.class, fi.pyramus.rest.tranquil.students.StudentVariableEntity.class);
    classes.put(fi.pyramus.domainmodel.base.Nationality.class, fi.pyramus.rest.tranquil.base.NationalityEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseUser.class, fi.pyramus.rest.tranquil.courses.CourseUserEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.CourseAssessmentRequest.class, fi.pyramus.rest.tranquil.grading.CourseAssessmentRequestEntity.class);
    classes.put(fi.pyramus.domainmodel.file.File.class, fi.pyramus.rest.tranquil.file.FileEntity.class);
    classes.put(fi.pyramus.domainmodel.system.Setting.class, fi.pyramus.rest.tranquil.system.SettingEntity.class);
    classes.put(fi.pyramus.domainmodel.base.Tag.class, fi.pyramus.rest.tranquil.base.TagEntity.class);
    classes.put(fi.pyramus.domainmodel.base.CourseBaseVariable.class, fi.pyramus.rest.tranquil.base.CourseBaseVariableEntity.class);
    classes.put(fi.pyramus.domainmodel.projects.Project.class, fi.pyramus.rest.tranquil.projects.ProjectEntity.class);
    classes.put(fi.pyramus.domainmodel.resources.Resource.class, fi.pyramus.rest.tranquil.resources.ResourceEntity.class);
    classes.put(fi.pyramus.domainmodel.system.SettingKey.class, fi.pyramus.rest.tranquil.system.SettingKeyEntity.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntryEntityProperty.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryEntityPropertyEntity.class);
    classes.put(fi.pyramus.domainmodel.base.ComponentBase.class, fi.pyramus.rest.tranquil.base.ComponentBaseEntity.class);
    classes.put(fi.pyramus.domainmodel.resources.MaterialResource.class, fi.pyramus.rest.tranquil.resources.MaterialResourceEntity.class);
    classes.put(fi.pyramus.domainmodel.base.StudyProgrammeCategory.class, fi.pyramus.rest.tranquil.base.StudyProgrammeCategoryEntity.class);
    classes.put(fi.pyramus.domainmodel.base.EducationType.class, fi.pyramus.rest.tranquil.base.EducationTypeEntity.class);
    classes.put(fi.pyramus.domainmodel.base.ContactURL.class, fi.pyramus.rest.tranquil.base.ContactURLEntity.class);
    classes.put(fi.pyramus.domainmodel.base.Address.class, fi.pyramus.rest.tranquil.base.AddressEntity.class);
    classes.put(fi.pyramus.domainmodel.users.InternalAuth.class, fi.pyramus.rest.tranquil.users.InternalAuthEntity.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntryEntity.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryEntityEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.ProjectAssessment.class, fi.pyramus.rest.tranquil.grading.ProjectAssessmentEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.GradingScale.class, fi.pyramus.rest.tranquil.grading.GradingScaleEntity.class);
    classes.put(fi.pyramus.domainmodel.base.MagicKey.class, fi.pyramus.rest.tranquil.base.MagicKeyEntity.class);
    classes.put(fi.pyramus.domainmodel.base.SchoolVariable.class, fi.pyramus.rest.tranquil.base.SchoolVariableEntity.class);
    classes.put(fi.pyramus.domainmodel.projects.ProjectModule.class, fi.pyramus.rest.tranquil.projects.ProjectModuleEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseComponentResource.class, fi.pyramus.rest.tranquil.courses.CourseComponentResourceEntity.class);
    classes.put(fi.pyramus.domainmodel.users.User.class, fi.pyramus.rest.tranquil.users.UserEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseEnrolmentType.class, fi.pyramus.rest.tranquil.courses.CourseEnrolmentTypeEntity.class);
    classes.put(fi.pyramus.domainmodel.base.ContactURLType.class, fi.pyramus.rest.tranquil.base.ContactURLTypeEntity.class);
    classes.put(fi.pyramus.domainmodel.modules.Module.class, fi.pyramus.rest.tranquil.modules.ModuleEntity.class);
    classes.put(fi.pyramus.domainmodel.users.UserVariable.class, fi.pyramus.rest.tranquil.users.UserVariableEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentGroup.class, fi.pyramus.rest.tranquil.students.StudentGroupEntity.class);
    classes.put(fi.pyramus.domainmodel.base.AcademicTerm.class, fi.pyramus.rest.tranquil.base.AcademicTermEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.GradeCourseResource.class, fi.pyramus.rest.tranquil.courses.GradeCourseResourceEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseComponent.class, fi.pyramus.rest.tranquil.courses.CourseComponentEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseParticipationType.class, fi.pyramus.rest.tranquil.courses.CourseParticipationTypeEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentGroupUser.class, fi.pyramus.rest.tranquil.students.StudentGroupUserEntity.class);
    classes.put(fi.pyramus.domainmodel.help.HelpFolder.class, fi.pyramus.rest.tranquil.help.HelpFolderEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.Course.class, fi.pyramus.rest.tranquil.courses.CourseEntity.class);
    classes.put(fi.pyramus.domainmodel.reports.Report.class, fi.pyramus.rest.tranquil.reports.ReportEntity.class);
    classes.put(fi.pyramus.domainmodel.help.HelpItemTitle.class, fi.pyramus.rest.tranquil.help.HelpItemTitleEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseDescriptionCategory.class, fi.pyramus.rest.tranquil.courses.CourseDescriptionCategoryEntity.class);
    classes.put(fi.pyramus.domainmodel.changelog.TrackedEntityProperty.class, fi.pyramus.rest.tranquil.changelog.TrackedEntityPropertyEntity.class);
    classes.put(fi.pyramus.domainmodel.base.SchoolVariableKey.class, fi.pyramus.rest.tranquil.base.SchoolVariableKeyEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.CreditVariable.class, fi.pyramus.rest.tranquil.grading.CreditVariableEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentEducationalLevel.class, fi.pyramus.rest.tranquil.students.StudentEducationalLevelEntity.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntryProperty.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryPropertyEntity.class);
    classes.put(fi.pyramus.domainmodel.file.FileType.class, fi.pyramus.rest.tranquil.file.FileTypeEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentExaminationType.class, fi.pyramus.rest.tranquil.students.StudentExaminationTypeEntity.class);
    classes.put(fi.pyramus.domainmodel.modules.ModuleComponent.class, fi.pyramus.rest.tranquil.modules.ModuleComponentEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.OtherCost.class, fi.pyramus.rest.tranquil.courses.OtherCostEntity.class);
    classes.put(fi.pyramus.domainmodel.plugins.PluginRepository.class, fi.pyramus.rest.tranquil.plugins.PluginRepositoryEntity.class);
    classes.put(fi.pyramus.domainmodel.base.EducationSubtype.class, fi.pyramus.rest.tranquil.base.EducationSubtypeEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseUserRole.class, fi.pyramus.rest.tranquil.courses.CourseUserRoleEntity.class);
    classes.put(fi.pyramus.domainmodel.changelog.ChangeLogEntry.class, fi.pyramus.rest.tranquil.changelog.ChangeLogEntryEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.CreditLink.class, fi.pyramus.rest.tranquil.grading.CreditLinkEntity.class);
    classes.put(fi.pyramus.domainmodel.plugins.Plugin.class, fi.pyramus.rest.tranquil.plugins.PluginEntity.class);
    classes.put(fi.pyramus.domainmodel.base.CourseEducationSubtype.class, fi.pyramus.rest.tranquil.base.CourseEducationSubtypeEntity.class);
    classes.put(fi.pyramus.domainmodel.base.PhoneNumber.class, fi.pyramus.rest.tranquil.base.PhoneNumberEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentActivityType.class, fi.pyramus.rest.tranquil.students.StudentActivityTypeEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseState.class, fi.pyramus.rest.tranquil.courses.CourseStateEntity.class);
    classes.put(fi.pyramus.domainmodel.students.Student.class, fi.pyramus.rest.tranquil.students.StudentEntity.class);
    classes.put(fi.pyramus.domainmodel.base.StudyProgramme.class, fi.pyramus.rest.tranquil.base.StudyProgrammeEntity.class);
    classes.put(fi.pyramus.domainmodel.resources.ResourceCategory.class, fi.pyramus.rest.tranquil.resources.ResourceCategoryEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.StudentCourseResource.class, fi.pyramus.rest.tranquil.courses.StudentCourseResourceEntity.class);
    classes.put(fi.pyramus.domainmodel.base.Defaults.class, fi.pyramus.rest.tranquil.base.DefaultsEntity.class);
    classes.put(fi.pyramus.domainmodel.base.Language.class, fi.pyramus.rest.tranquil.base.LanguageEntity.class);
    classes.put(fi.pyramus.domainmodel.base.CourseEducationType.class, fi.pyramus.rest.tranquil.base.CourseEducationTypeEntity.class);
    classes.put(fi.pyramus.domainmodel.base.Municipality.class, fi.pyramus.rest.tranquil.base.MunicipalityEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseStudent.class, fi.pyramus.rest.tranquil.courses.CourseStudentEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.TransferCreditTemplateCourse.class, fi.pyramus.rest.tranquil.grading.TransferCreditTemplateCourseEntity.class);
    classes.put(fi.pyramus.domainmodel.base.CourseBaseVariableKey.class, fi.pyramus.rest.tranquil.base.CourseBaseVariableKeyEntity.class);
    classes.put(fi.pyramus.domainmodel.drafts.FormDraft.class, fi.pyramus.rest.tranquil.drafts.FormDraftEntity.class);
    classes.put(fi.pyramus.domainmodel.help.HelpItem.class, fi.pyramus.rest.tranquil.help.HelpItemEntity.class);
    classes.put(fi.pyramus.domainmodel.base.CourseBase.class, fi.pyramus.rest.tranquil.base.CourseBaseEntity.class);
    classes.put(fi.pyramus.domainmodel.students.AbstractStudent.class, fi.pyramus.rest.tranquil.students.AbstractStudentEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.BasicCourseResource.class, fi.pyramus.rest.tranquil.courses.BasicCourseResourceEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseStudentVariable.class, fi.pyramus.rest.tranquil.courses.CourseStudentVariableEntity.class);
    classes.put(fi.pyramus.domainmodel.projects.StudentProject.class, fi.pyramus.rest.tranquil.projects.StudentProjectEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentGroupStudent.class, fi.pyramus.rest.tranquil.students.StudentGroupStudentEntity.class);
    classes.put(fi.pyramus.domainmodel.base.EducationalTimeUnit.class, fi.pyramus.rest.tranquil.base.EducationalTimeUnitEntity.class);
    classes.put(fi.pyramus.domainmodel.courses.CourseStudentVariableKey.class, fi.pyramus.rest.tranquil.courses.CourseStudentVariableKeyEntity.class);
    classes.put(fi.pyramus.domainmodel.base.ContactType.class, fi.pyramus.rest.tranquil.base.ContactTypeEntity.class);
    classes.put(fi.pyramus.domainmodel.base.Email.class, fi.pyramus.rest.tranquil.base.EmailEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.Credit.class, fi.pyramus.rest.tranquil.grading.CreditEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.Grade.class, fi.pyramus.rest.tranquil.grading.GradeEntity.class);
    classes.put(fi.pyramus.domainmodel.file.StudentFile.class, fi.pyramus.rest.tranquil.file.StudentFileEntity.class);
    classes.put(fi.pyramus.domainmodel.students.StudentImage.class, fi.pyramus.rest.tranquil.students.StudentImageEntity.class);
    classes.put(fi.pyramus.domainmodel.base.EducationalLength.class, fi.pyramus.rest.tranquil.base.EducationalLengthEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.TransferCreditTemplate.class, fi.pyramus.rest.tranquil.grading.TransferCreditTemplateEntity.class);
    classes.put(fi.pyramus.domainmodel.grading.CourseAssessment.class, fi.pyramus.rest.tranquil.grading.CourseAssessmentEntity.class);
    classes.put(fi.pyramus.domainmodel.base.Subject.class, fi.pyramus.rest.tranquil.base.SubjectEntity.class);
    classes.put(fi.pyramus.domainmodel.base.SchoolField.class, fi.pyramus.rest.tranquil.base.SchoolFieldEntity.class);
  }

  @Override
  public Class<?> findTranquilModel(Class<?> entity) {
    return classes.get(entity);
  }

  private java.util.Map<Class<?>, Class<?>> classes =  new java.util.HashMap<Class<?>, Class<?>>();
}
